# docker-compose.yaml
version: '3'

services:
  app:
    build:   { context: . }
    ports:   [ '8000:8000' ]
    links:   [ database ]
    volumes: [ '.:/www' ]

  database:
    image: postgres:9.6-alpine
    volumes: ['database:/var/lib/postgresql/data']
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo

volumes:
  database: ~
